index:
    path: /
    controller: App\Controller\DefaultController::index
form:
    path: /form
    controller: App\Controller\DefaultController::registerAction
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\Lucky::number
list:
    path: /users/list
    controller: App\Controller\DefaultController::showAction
delete:
    path: /users/delete/{id}
    controller: App\Controller\DefaultController::deleteAction
edit:
    path: /users/edit/{id}
    controller: App\Controller\DefaultController::editAction
json:
    path: /json/list
    controller: App\Controller\DefaultController::jsonAction

